# Generated by Django 4.1.7 on 2023-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100, verbose_name='Клиент')),
                ('contact', models.CharField(max_length=100, verbose_name='Контакты')),
                ('title', models.CharField(max_length=100, verbose_name='Вид\\модель техники')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(blank=True, max_length=60, verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
