# Generated by Django 4.1.7 on 2023-09-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Диагностика', max_length=60, verbose_name='Статус'),
        ),
    ]
