# Generated by Django 4.1.7 on 2023-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-time_create'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Диагностика', 'Диагностика'), ('В работе', 'В работе'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='Диагностика', max_length=60, verbose_name='Статус'),
        ),
    ]
