# Generated by Django 4.1.7 on 2023-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Контакты'),
        ),
    ]
