# Generated by Django 4.1.7 on 2023-10-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_order_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Касса')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='expenses',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Затраты'),
        ),
    ]
