# Generated by Django 4.1.7 on 2023-10-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_cash_order_expenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cash',
        ),
    ]
