# Generated by Django 4.1.7 on 2023-11-02 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0012_alter_expenses_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='author',
        ),
        migrations.AddField(
            model_name='expenses',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='Expenses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
