# Generated by Django 4.1.7 on 2023-11-02 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0015_alter_expenses_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Expenses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
